<?xml version="1.0" encoding="UTF-8" ?>
<container xmlns="http://symfony.com/schema/dic/services"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">
    <services>
        <service
            id="Phpro\ApiProblemBundle\EventListener\JsonApiProblemExceptionListener"
            class="Phpro\ApiProblemBundle\EventListener\JsonApiProblemExceptionListener"
        >
            <argument key="$exceptionTransformer" type="service" id="Phpro\ApiProblemBundle\Transformer\Chain" />
            <argument key="$debug" >%kernel.debug%</argument>
            <tag name="kernel.event_listener" event="kernel.exception" method="onKernelException" priority="-5" />
        </service>
        <service id="Phpro\ApiProblemBundle\Transformer\Chain" class="Phpro\ApiProblemBundle\Transformer\Chain">
            <argument type="tagged_iterator" tag="phpro.api_problem.exception_transformer" />
        </service>
        <service id="Phpro\ApiProblemBundle\Transformer\ApiProblemExceptionTransformer" class="Phpro\ApiProblemBundle\Transformer\ApiProblemExceptionTransformer">
            <tag name="phpro.api_problem.exception_transformer" />
        </service>
        <service id="Phpro\ApiProblemBundle\Transformer\HttpExceptionTransformer" class="Phpro\ApiProblemBundle\Transformer\HttpExceptionTransformer">
            <tag name="phpro.api_problem.exception_transformer" />
        </service>
        <service id="Phpro\ApiProblemBundle\Transformer\SecurityExceptionTransformer" class="Phpro\ApiProblemBundle\Transformer\SecurityExceptionTransformer">
            <tag name="phpro.api_problem.exception_transformer" />
        </service>
    </services>
</container>
